#!/bin/bash
# This script will copy all the configure files into your system

echo "Copying all the configures..."

if [[ `uname` == Drawin ]]; then
	cp .bashrc ~/.profile
else
	cp .bashrc ~/
fi

echo "Copying configures to $HOME"
cp .tmux.conf .bashrc ~/
cp -r bin ~/
cp myemacs/_emacs_linux ~/.emacs

if [ ! -e ~/proj/work/raysconfig/myemacs/snippets ]
then
  mkdir ~/proj/work/raysconfig/myemacs/snippets
fi
